### ISSUE TITLE
Missing config?

### ISSUE THREAD

**Issue by penturt** [Darkhax-Minecraft/Tool-Stats#12]
If I'm wrong I'm sorry, but when I used the Tool-Stats mod for 1.16 it would show me the durability of tools, weapons, etc... I just started using the 1.18 version and notice it doesn't and when I went to check the config file, it's blank, is this working as expected or am I completely wrong?

**Comment by Darkhax** [comment]
Hello, thank you for reporting this issue. You are correct this is an issue with the mod and I have pushed an update to fix it. https://github.com/Darkhax-Minecraft/Tool-Stats/commit/cd6806290cb454363261f888328b29e73a4f6239

- [Forge File](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/3631495)
- [Fabric File](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/3631494)
