### ISSUE TITLE
ru_ru.lang

### ISSUE THREAD

**Issue by aigiz010** [Darkhax-Minecraft/Tool-Stats#13]
[ru_ru.zip](https://github.com/Darkhax-Minecraft/Tool-Stats/files/7969743/ru_ru.zip)

**Comment by Darkhax** [comment]
Thanks for helping translate this mod. A new update has been put out https://github.com/Darkhax-Minecraft/Tool-Stats/commit/c3e537e59dfd62fc4f7954c8401ff1971d7f2115
