### ISSUE TITLE
Additional Additions incompatibility

### ISSUE THREAD

**Issue by Dqu1J** [Darkhax-Minecraft/Tool-Stats#16]
This mod doesn't work with Additional Additions properly when AdAd's datapacks are used, which update the stats of the tools dynamically on world load for each tool independently from it's tier, which includes dig speed, for example. ToolStats displays the default stats of the tools, instead of the updated ones.   
 
For reference:
- [AdAd fabric repo](https://github.com/Additional-Mods/additionaladditions)
- [AdAd forge repo](https://github.com/Additional-Mods/additionaladditions-forge)
- [AdAd datapack behaviour wiki](https://github.com/Additional-Mods/additionaladditions/wiki/Datapack-Behaviours)
- [Example datapack for testing (changes rose gold pickaxe mining speed to 8 from 9)](https://www.mediafire.com/file/ypk99xt5sb8xfd1/additionaladditions.zip/file)

**Comment by Darkhax** [comment]
Unfortunately these types of mods often change things in a way that can not be easily detected or made displayable. In newer versions I've improved compatibility for dig speed however I can not guarantee compatibility for every way that these mods may change an item.

**Comment by Dqu1J** [comment]
Got it, and thanks!
