### ISSUE TITLE
[Request] blacklist to hide sertain stats from sertain items.

### ISSUE THREAD

**Issue by murao-kun** [Darkhax-Minecraft/Tool-Stats#20]
On the mod page there is information that:
Mining Efficiency (Only on tiered items like pickaxe)
Harvest Level (Only on tiered items like pickaxe)

But stats are showing on even non tired items like swords.
I am playing on version 1.19.2 Forge.

Even if it is not a bug, information is pointless on them.
I hope you consider fix that or add blacklist.
Thank you for amazing mod!

**Comment by Darkhax** [comment]
Hello, 

This is actually working as intended. Swords are a tiered item and have a harvest level and mining efficiency stat. The sword is also a valid mining tool type and is listed as the preferred tool for blocks like cobwebs. Modded blocks make further use of this.

**Comment by murao-kun** [comment]
Hmm. Let's change that to request to have blacklist. The mod is being pretty useful for tools. But still pretty useless for weapons in my modpack. Every sword is be able to dig down cobweb, there is no need to know it's harvest level or digging speed. But enchantability is being still useful.

**Comment by murao-kun** [comment]
I thought I can just ignore that stats and not ask for a feature like that, but after remaking combat mechanics I can't mine with weapons, so I still need that feature.
Suggesting to make a config file with the array of items that will be ignored to show any tooltips from this mod.

**Comment by Darkhax** [comment]
I will add this to my TODO list however I do not have an ETA for when I will get around to it.

**Comment by murao-kun** [comment]
Not a problem at least you that is in your TODO list.

**Comment by Darkhax** [comment]
Looking into it, you can already disable certain types of information from showing up on certain tools by giving the tool an item tag. 

- `toolstats:ignored`
- `toolstats:ignore_dig_speed`
- `toolstats:ignore_durability`
- `toolstats:ignore_enchantability`
- `toolstats:ignore_harvest_level`
- `toolstats:ignore_repair_cost`

**Comment by murao-kun** [comment]
Thank you!!
