### ISSUE TITLE
[1.18.2] Apotheosis Weapons

### ISSUE THREAD

**Issue by INooBTooMuch** [Darkhax-Minecraft/Tool-Stats#22]
[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis) affixed weapons with changed Attack Damage or Attack Speed have those stats show multiple times. 

Mod Version : ToolStats-Forge-1.18.2-9.0.3

![2022-09-08_14 41 33](https://user-images.githubusercontent.com/107572028/189114758-13dbca0c-ea34-45ec-8781-c9e588c3d29a.png)

**Comment by Darkhax** [comment]
Thanks for letting me know. This bug is related to #21 and will be fixed soon.
