### ISSUE TITLE
[Suggestion] Add colors settings to durability

### ISSUE THREAD

**Issue by Yashirow** [Darkhax-Minecraft/Tool-Stats#25]
Hi,
Could it be possible to have some colors settings for the durability ? I thought that the grey one already present in the description of items (When in main hand) would be better than the default white.
![image](https://user-images.githubusercontent.com/100087778/207881983-c4cbdcd6-3622-4a81-8cfe-d01eea6ccfae.png)
Thanks !

**Comment by Darkhax** [comment]
Hello, the tooltip color was meant to be grey like the vanilla one. This has been fixed in 1.19.4. Config options to style this however would be cool but there are some technical things to consider, I will put it on my backlog for a future update.
