### ISSUE TITLE
Fabric 1.19.3 support

### ISSUE THREAD

**Issue by lospejos** [Darkhax-Minecraft/Tool-Stats#26]
Please upgrade to support Fabric 1.19.3. Thanks!

**Comment by Darkhax** [comment]
Thanks for the request, I will soon.

**Comment by Darkhax** [comment]
Tool Stats 13.0.1 is now out. It supports 1.19.3 for [Forge](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4318500) and [Fabric](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4318499).
