### ISSUE TITLE
1.19.2 Crash on launch[No other mods installed besides Bookshelf] 

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/Tool-Stats#27]
1.19.2 Forge 43.2.0
ToolStats-Forge-1.19.2-12.0.2

Error
-----------------------------------------------
ToolStats (toolstats) has failed to load correctly
java.lang.reflect.InvocationTargetException; null
----------------------------------------------

**Comment by Darkhax** [comment]
Please include the full crash log.

**Comment by ghost** [comment]
Same here

**Comment by Darkhax** [comment]
@vuflub2 Please create a new issue report with your crash log.
