### ISSUE TITLE
[1.16.5] [bug] Incompatible with mod Property Modifier

### ISSUE THREAD

**Issue by GoldenTotem** [Darkhax-Minecraft/Tool-Stats#28]
Mod [Property Modifier](https://www.curseforge.com/minecraft/mc-mods/property-modifier) can be used to modify harvest level and efficiency of tools. But this mod toolstats can not display the changed value, it still display previous value. For example, I used Property Modifier to change the efficiency of diamond pickaxe from 8 to 80, actually diamond pickaxe can break blocks very quickly but it still display that the efficiency of diamond pickaxe was 8. It's same with harvest level.

**Comment by Darkhax** [comment]
Unfortunately these types of mods change the tools in ways that are not easily detected or displayable. In newer versions I've improved the digging speed detection and I've backported that fix now, however I can not guarantee perfect compatibility for every way that these mods may change an item.
