### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by SorkoPiko** [Darkhax-Minecraft/Tool-Stats#30]
Hey, I have been using your mods, and was wondering if you could update this mod to 1.20-1.20.1. I would love to use this mod again, as I have had to remove it from my mods folder for my minecraft to boot. As there are no new tools in this update, it should be pretty easy to update (I've never written a mod though, so I don't know). Thanks again, and hopefully I didn't bother you.

**Comment by Darkhax** [comment]
Thanks for the requests. Updates are coming but they are going to be a bit slower than they have been in the past. While the port will be very simple there were a lot of updates to the tools we use to create and publish mods that I want to implement.
