### ISSUE TITLE
Not a problem with your mod

### ISSUE THREAD

**Issue by logitechQ** [Darkhax-Minecraft/Tool-Stats#39]
Do you know how to hide these last remaining stats? I got a lot of other stats and the tooltip is getting kinda full, your mod is already hiding some so i'm thankful for it
![Stats](https://github.com/Darkhax-Minecraft/Tool-Stats/assets/47274387/e10b64f8-5d76-4323-a899-ff60df052a73)

**Comment by Darkhax** [comment]
Hello, I am not really sure what you mean. This mod adds more info instead of hiding/removing info. I am not sure of any premade mods that remove those tooltip entries but I know that you can write a pretty simple CraftTweaker script to completely customize it.
