### ISSUE TITLE
[Suggestion] Enchantment efficiency can change efficiency value

### ISSUE THREAD

**Issue by GoldenTotem** [Darkhax-Minecraft/Tool-Stats#40]
Minecraft 1.16.5  Forge 36.2.35  ToolStats 6.1.6
Enchantment sharpness can improve attack damage value in vanilla, maybe enchantment efficiency should also be that case.

**Comment by memphismc** [comment]
i second this! would be a dope change

**Comment by Darkhax** [comment]
Thanks for the suggestion. I've pushed an update for 1.20.1 that includes this feature. I will backport this to the older versions of the game soon.

**Comment by Darkhax** [comment]
Okay this feature should now be live for the old versions as well.

- 1.16.5 should use [6.1.7](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4957714)
- 1.18.2 should use 9.0.4 for [forge](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4957711) and [fabric](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4957710)
- 1.19.2 should use 12.1.5 for [forge](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4957688) and [fabric](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4957683)
- 1.19.4 should use 14.1.6 for [forge](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4957661) and [fabric](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4957660)
- 1.20.1 should use 16.0.4 for [forge](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4774979) and [fabric](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/4774978)
