### ISSUE TITLE
Suggestion: add config to disable Sharpness damage adjustment

### ISSUE THREAD

**Issue by Partonetrain** [Darkhax-Minecraft/Tool-Stats#41]
Vanilla automatically adjusts the Attack Damage line to match the output of an attack with the Sharpness enchantment, and I suggest that this mod should have an option to disable that.
"Why would anyone want this?"
Consistency with Minecraft Dungeons.

**Comment by Darkhax** [comment]
Thanks for the suggestion. I've looked into this a bit and while it would be possible to add I think it's a out of scope for what this mod is trying to do. There are a lot of inconsistencies between the tooltips in Java Edition and Dungeons so it would probably be better to use a mod that's dedicated to making them more consistent.
