### ISSUE TITLE
[FEEDBACK] 1.17.1 forge port

### ISSUE THREAD

**Issue by sbevesbren** [Darkhax-Minecraft/Tool-Stats#43]
### Minecraft Version

1.17.1

### Mod Loader

Forge

### Feedback

could you please port the mod to forge 1.17.1

**Comment by Darkhax** [comment]
Hello, 1.17.1 is nearly 3 years old so a lot of the tools used to make mods for that version have moved or are no longer available. I don't have the time right now to work on this, but if someone else wants to make a valid pull request I will look into it.
