### ISSUE TITLE
[QUESTION] Why is every hoe only shows "1" digging speed?

### ISSUE THREAD

**Issue by liangmoe** [Darkhax-Minecraft/Tool-Stats#44]
### Question

I noticed every hoe only have 1 digging speed even they are actually dig faster when they comes with higher level's hoe, so im asking here
Im using neoforge 1.20.1-47.100 with [the latest toolstats](https://modrinth.com/mod/tool-stats/version/qBJfkjnM)
![2024-02-25_19 23 02](https://github.com/Darkhax-Minecraft/Tool-Stats/assets/135343248/2747b266-3c87-430c-beb3-36895af5dafd)
![2024-02-25_19 23 00](https://github.com/Darkhax-Minecraft/Tool-Stats/assets/135343248/bc858dbf-90e9-4187-80a3-ca7ff897dc42)

![2024-02-25_19 23 01](https://github.com/Darkhax-Minecraft/Tool-Stats/assets/135343248/b1fe668b-2522-4563-a35e-bf15745e4974)

**Comment by Darkhax** [comment]
Thanks for finding this, we were comparing the speeds against the mushroom block but apparently the hoe is not effective against those. I've released a new update for 1.20.4 and will backport the fix to a few older versions soon.

**Comment by Darkhax** [comment]
The fix for Forge/NeoForge 1.20.1 can be found [here](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/5136223).

**Comment by GoldenTotem** [comment]
> Thanks for finding this, we were comparing the speeds against the mushroom block but apparently the hoe is not effective against those. I've released a new update for 1.20.4 and will backport the fix to a few older versions soon.

Also reproduce this at 1.16.5. Looking forward to backport the fix to 1.16.5
