### ISSUE TITLE
[Suggestion] config option to always show enchantability

### ISSUE THREAD

**Issue by Zygus42** [Darkhax-Minecraft/Tool-Stats#6]
I personally would love to be able to see the enchantability of items without having to put them one by one into the enchanting table.  Any chance of adding a config option to allow enchantability to be shown as per the other stats ?

**Comment by Darkhax** [comment]
Hello, 

I will add this and maybe some other features in the next update.

**Comment by Darkhax** [comment]
This feature was added in [5.0.2](https://www.curseforge.com/minecraft/mc-mods/tool-stats/files/3185520)
