### ISSUE TITLE
Interferes with appleskin saturation tooltip

### ISSUE THREAD

**Issue by TestSerber** [Darkhax-Minecraft/Tool-Stats#9]
Title says, sorry for short issue.

**Comment by Darkhax** [comment]
Could you include some more info about this? In what ways does it interfere? Is it a crash or something visual, etc.

**Comment by TestSerber** [comment]
the tooltip for saturation bars no longer appear in REI, sorry made this issue quite rushed and forgot to come back to it

**Comment by Darkhax** [comment]
After several months of testing, I have not been able to reproduce this issue. Please update the mods involved, it may have been fixed on their end or something. If there is more specific information such as versions of the mods involved and screenshots of the issue please re-open this issue.
